[tool.poetry]
name = "demo-vidgear-application"
version = "0.0.1"
description = ""
authors = ["Alessio Locatelli <148966056+alessio-locatelli@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.12.6"
numpy = "^2.1.2"
opencv-python = "^4.10.0.84"
vidgear = "^0.3.3"
